FROM python:3.10

RUN apt-get update && apt-get install -y \
build-essential \
cmake \
libsm6 \
libxext6 \
libxrender-dev \
libgl1 \
libglib2.0-0 \
libx11-6

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]